import Head from "next/head";
import Message from "../../conponents/message"
import { useEffect, useState } from "react";
import { db } from "../../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Link from "next/link";

import { AiOutlineLike, AiOutlineDislike } from 'react-icons/ai'
import { FaRegComments } from 'react-icons/fa'


export default function Home()
{
  const [allPosts, setAllPosts] = useState([]);
  const [selection, setSelection] = useState(null);

  const [count, setCount] = useState(0);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    });
    return unsubscribe;
  };


  useEffect(() => {
    getPosts()
  }, [])
  

  const handleSelection = (option) => {
  if (selection === option) {
    setSelection(null); // Deselect if already selected
    if (option === 'in') {
      setCount(count - 1);
    }
  } else {
    setSelection(option);
    if (option === 'in') {
      setCount(count + 1);
    } else if (option === 'out') {
      // Do nothing if the previous selection was also "Out"
    } else {
      setCount(count - 1);
    }
  }
}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 mx-12 text-lg font-medium">
        <h2>upcoming events</h2>
        {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <div
              className="flex justify-end mb-2"
            >
              <Link
                href={{ pathname: `/${post.id}`, query: { ...post } }}
                className="border-2 w-1/3 flex justify-center sm:w-1/5">
                {post.comments?.length > 0 ? post.comments?.length : 0} comments <FaRegComments />
              </Link>
              

            </div>

            <div className="flex justify-end gap-2">

              <div className="text-lg rounded-full font-bold m-4">{count}</div>
              
              <button
                onClick={() => handleSelection('in')} disabled={selection === 'out'}
                // className="bg-blue-500 hover:bg-blue-700 text-white font-bold px-4 rounded focus:outline-none focus:shadow-outline w-20 flex py-4 gap-2"
                className={`${selection === 'in' ?
                  'bg-blue-500 hover:bg-blue-700 text-white font-bold px-4 rounded focus:outline-none focus:shadow-outline w-20 flex py-4 gap-2'
                  : 'border-2 border-blue-500 hover:bg-blue-700 text-blue-500 font-bold px-4 rounded focus:outline-none focus:shadow-outline w-20 flex py-4 gap-2'} 
                `}
              >
                <AiOutlineLike className="mt-1.5" />
                In
              </button>
              
              <button
                onClick={() => handleSelection('out')} disabled={selection === 'in'}
                className={`${selection === 'out' ?
                  "bg-red-500 hover:bg-red-700 text-white font-bold px-3 rounded focus:outline-none focus:shadow-outline w-20 flex py-4"
                  :
                  "border-2 border-red-500 hover:bg-red-700 text-red-500 font-bold px-3 rounded focus:outline-none focus:shadow-outline w-20 flex py-4"
              }`}
               
              >
                <AiOutlineDislike className="mt-1.5 w-20"/>
                Out
              </button>
            </div>



          </Message>
        ))}
      </div>
    </>
  )
}
